baseURL = "https://doggor.github.io/"
languageCode = "zh-cmn-Hans"
title = "ç¢¼è¾²ç”Ÿæ´»"
theme = "m10c"
enableRobotsTXT = true
hasCJKLanguage = true
enableEmoji = true
disqusShortname = "doggor-coding-notebook"

[params]
  author = "Doggor"
  description = "ä¸€éš»ITğŸ¶çš„è¸©å‘ç­†è¨˜"
  [[params.social]]
    name = "github"
    url = "https://github.com/doggor"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/andy-ching-hk"
  [params.style]
    darkestColor = "#16191d"
    darkColor = "#242930"
    lightColor = "#afbac4"
    lightestColor = "#ffd600"
    primaryColor = "#ffd600"
